### ISSUE TITLE
Won't Engrave Runes, Equipment Slot Error

### ISSUE THREAD

**Issue by MorteDeAngelis** [mcd8604/wowengraver#17]
When trying to engrave runes using the Interface it'll show an error that there is no equipment in the slot.

This happens regardless of settings and is happening for me and a friend, we only recently found the add-on so unsure if this was a bug prior to SoD Season 4.

We also checked and the error still occurs even if Engraver is the only add on loaded.

I will check regularly if you require any more information

**Comment by mcd8604** [comment]
I am not able to reproduce the bug - it's working fine for me. Can you share the contents of your settings file please? 
C:\Program Files (x86)\World of Warcraft\_classic_era_\WTF\Account\AccountName\SavedVariables\Engraver.lua
and
C:\Program Files (x86)\World of Warcraft\_classic_era_\WTF\Account\AccountName\ServerName\CharacterName\SavedVariables\Engraver.lua

also.. just to make sure.. do you have a piece of gear equipped to that slot?

also, are you running the latest version of Engraver? (v1.15.0)

**Comment by MorteDeAngelis** [comment]
EngraverOptions = {
["ShowFilterSelector"] = false,
["UseCharacterSpecificSettings"] = false,
["HideTooltip"] = false,
["UIScale"] = 1,
["CurrentFilter"] = 0,
["HideSlotLabels"] = false,
["DisplayMode"] = 1,
["HideDragTab"] = false,
["PreventSpellPlacement"] = false,
["HideUndiscoveredRunes"] = false,
["EnableRightClickDrag"] = false,
["VisibilityMode"] = "ShowAlways",
["LayoutDirection"] = 0,
}


EngraverFilters = {
["Paladin"] = {
},
}
EngraverSharedOptions = {
["ShowFilterSelector"] = false,
["HideSlotLabels"] = false,
["HideTooltip"] = false,
["LayoutDirection"] = 1,
["DisplayMode"] = 0,
["HideDragTab"] = true,
["UIScale"] = 1,
["HideUndiscoveredRunes"] = false,
["EnableRightClickDrag"] = true,
["VisibilityMode"] = "ShowOnMouseOver",
["PreventSpellPlacement"] = false,
}

Yes, I do have a piece of gear in the slot :P
Yes, its version 1.15.0 according to curseforge

**Comment by mercurito** [comment]
I have the same issue as well. Won't engrave rune, equipment slot is empty.

Did you by any chance reroll? Deleted toon and created it again with the same name? I did that. Not sure if that may be related to the issue.

Edit: looks like my other toons don't have this issue. For some reason this toon gets this error

**Comment by mcd8604** [comment]
> Did you by any chance reroll? Deleted toon and created it again with the same name? I did that. Not sure if that may be related to the issue.

Thanks, I didn't think of creating a new toon to test with. Once I did, I was able to reproduce the bug. I was able to fix it and you should be able to update now.

**Comment by MorteDeAngelis** [comment]
Thanks, can confirm it works.  :)
