### ISSUE TITLE
Phase 5 - 

### ISSUE THREAD

**Issue by maitlandatiesh** [mcd8604/wowengraver#18]
**Describe the bug**
LUA errors with P5. , latest version 1.15.6

**To Reproduce**
At startup

**Expected behavior**

**Screenshots**

**List the version of the addon (release/beta).**

**Additional context**

**Error Output**
If you can, provide any Lua errors that you encounter in game. The BugGrabber and BugSack addons make this easy.

3x Blizzard_Settings_Shared/Blizzard_Setting.lua:3: assertion failed!
[string "=[C]"]: in function `assert'
[string "@Blizzard_Settings_Shared/Blizzard_Setting.lua"]:3: in function <Blizzard_Settings_Shared/Blizzard_Setting.lua:1>
[string "@Blizzard_Settings_Shared/Blizzard_Setting.lua"]:380: in function `Init'
[string "@Blizzard_SharedXMLBase/Mixin.lua"]:28: in function <Blizzard_SharedXMLBase/Mixin.lua:26>
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:197: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:155>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:98: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:97>
[string "=(tail call)"]: ?
[string "@Engraver/EngraverOptions.lua"]:149: in function `CreateSettingsInitializers'
[string "@Engraver/EngraverOptions.lua"]:70: in function <Engraver/EngraverOptions.lua:62>|

Locals:
(*temporary) = false

>>>>>>>

3x Blizzard_Settings_Shared/Blizzard_Setting.lua:383: 'variableTbl' argument must be a table.
[string "=[C]"]: in function `assert'
[string "@Blizzard_Settings_Shared/Blizzard_Setting.lua"]:383: in function `Init'
[string "@Blizzard_SharedXMLBase/Mixin.lua"]:28: in function <Blizzard_SharedXMLBase/Mixin.lua:26>
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:197: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:155>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:98: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:97>
[string "=(tail call)"]: ?
[string "@Engraver/EngraverOptions.lua"]:114: in function <Engraver/EngraverOptions.lua:113>
[string "@Engraver/EngraverOptions.lua"]:168: in function `CreateSettingsInitializers'
[string "@Engraver/EngraverOptions.lua"]:70: in function <Engraver/EngraverOptions.lua:62>

Locals:
(*temporary) = false
(*temporary) = "'variableTbl' argument must be a table."

>>>>>

3x Blizzard_Settings_Shared/Blizzard_Setting.lua:383: 'variableTbl' argument must be a table.
[string "=[C]"]: in function `assert'
[string "@Blizzard_Settings_Shared/Blizzard_Setting.lua"]:383: in function `Init'
[string "@Blizzard_SharedXMLBase/Mixin.lua"]:28: in function <Blizzard_SharedXMLBase/Mixin.lua:26>
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:197: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:155>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:98: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:97>
[string "=(tail call)"]: ?
[string "@Engraver/EngraverOptions.lua"]:114: in function <Engraver/EngraverOptions.lua:113>
[string "@Engraver/EngraverOptions.lua"]:168: in function `CreateSettingsInitializers'
[string "@Engraver/EngraverOptions.lua"]:70: in function <Engraver/EngraverOptions.lua:62>

Locals:
(*temporary) = false
(*temporary) = "'variableTbl' argument must be a table."

>>>>>

3x Engraver/EngraverOptions.lua:176: attempt to call field 'CreateDropDownInitializer' (a nil value)
[string "@Engraver/EngraverOptions.lua"]:176: in function `CreateSettingsInitializers'
[string "@Engraver/EngraverOptions.lua"]:70: in function <Engraver/EngraverOptions.lua:62>

Locals:
self = EngraverOptionsFrame {
 isSettingDefaults = false
 characterSpecificSettingsSetting = <table> {
 }
 layout = <table> {
 }
 initializers = <table> {
 }
 name = "Engraver"
 category = <table> {
 }
 engraverOptionsSettings = <table> {
 }
 settingsList = Frame {
 }
}
variable = "DisplayMode"
name = "Rune Display Mode"
tooltip = "How runes buttons are displayed."
tooltips = <table> {
 1 = "All runes are always shown."
 2 = "Show only one button for each engravable equipment slot. Move your cursor over any button to see the available runes."
}
setting = <table> {
 searchTags = <table> {
 }
 data = <table> {
 }
 frameTemplate = "EngraverCharacterSpecificControlTemplate"
}
(*temporary) = EngraverOptionsFrame {
 isSettingDefaults = false
 characterSpecificSettingsSetting = <table> {
 }
 layout = <table> {
 }
 initializers = <table> {
 }
 name = "Engraver"
 category = <table> {
 }
 engraverOptionsSettings = <table> {
 }
 settingsList = Frame {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 searchTags = <table> {
 }
 data = <table> {
 }
 frameTemplate = "EngraverCharacterSpecificControlTemplate"
}
(*temporary) = "How runes buttons are displayed."
(*temporary) = "attempt to call field 'CreateDropDownInitializer' (a nil value)"
Addon = <table> {
 EngraverDisplayModes = <table> {
 }
 EngraverVisibilityModes = <table> {
 }
 CategoryToSlotId = <table> {
 }
 EngraverLayoutDirections = <table> {
 }
 MasqueAdapter = <table> {
 }
 Filters = <table> {
 }
}

>>>>>

3x Engraver/EngraverOptions.lua:328: attempt to call method 'SetValue' (a nil value)
[string "@Engraver/EngraverOptions.lua"]:328: in function `HandleAddonLoaded'
[string "@Engraver/EngraverOptions.lua"]:286: in function <Engraver/EngraverOptions.lua:284>

Locals:
self = EngraverOptionsFrame {
 isSettingDefaults = false
 characterSpecificSettingsSetting = <table> {
 }
 layout = <table> {
 }
 initializers = <table> {
 }
 name = "Engraver"
 category = <table> {
 }
 engraverOptionsSettings = <table> {
 }
 settingsList = Frame {
 }
}
addonName = "Engraver"
(*temporary) = nil
(*temporary) = <table> {
 order = 9
 ID = "Engraver"
 categorySet = 2
 name = "Engraver"
 subcategories = <table> {
 }
}
(*temporary) = false
(*temporary) = "attempt to call method 'SetValue' (a nil value)"
localAddonName = "Engraver"
DefaultEngraverOptions = <table> {
 UseCharacterSpecificSettings = false
 CurrentFilter = 0
}
DefaultSettings = <table> {
 ShowFilterSelector = false
 PreventSpellPlacement = false
 HideSlotLabels = false
 LayoutDirection = 0
 DisplayMode = 1
 HideDragTab = false
 UIScale = 1
 HideUndiscoveredRunes = false
 EnableRightClickDrag = false
 VisibilityMode = "ShowAlways"
 HideTooltip = false
}

**Comment by mcd8604** [comment]
fixed by 18031a861c2f6f2cfcf16227df837118f54aa27f
