### ISSUE TITLE
Engraver Masque Error

### ISSUE THREAD

**Issue by KazDvs** [mcd8604/wowengraver#5]
Getting the following error with Engraver and Masque

1x Engraver/EngraverMasqueAdapter.lua:18: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Engraver/EngraverMasqueAdapter.lua"]:18: in function <Engraver/EngraverMasqueAdapter.lua:17>
[string "@Engraver/EngraverMasqueAdapter.lua"]:86: in function <Engraver/EngraverMasqueAdapter.lua:78>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:178: in function <SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@SharedXML/GlobalCallbackRegistry.lua"]:9: in function <SharedXML/GlobalCallbackRegistry.lua:8>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by mcd8604** [comment]
Thanks for the report. The fix is in as of [this release](/mcd8604/wowengraver/releases/tag/v1.12.15).
