### ISSUE TITLE
Spoiler for undiscovered Runes

### ISSUE THREAD

**Issue by celebrir** [mcd8604/wowengraver#8]
v1.13.3

While I appreciate the new menue with the Waist, Feet and Wrist runes, including the tooltips for all the datamined data from WoWhead, I do believe not everyone would like to have this spoiled. I for myself would not want to see the detailed tooltip info. At least not yet, even before P2 began.

For example, with Questie there was a popup window since the last update, asking if I want to have Rune Positions shown on the map of hidden. (Coudl be changed afterwards)

I'd like to have something like that. Maybe multiple levels:
1) Only show runes and rune slots I own / have discovered. (Means also don't show the slots if I have no rune of that type)
2) Show all available runes in the menu but neither the name, nor icon, nor tooltip. Just a gray "To be discovered" placehorder.
3) Show all available runes but only the names / icons
4) Show everything, as is now. All available information.

Alternatively, only 1) and 4)

**Comment by mcd8604** [comment]
There is already an option to Hide tooltips. These are the built-in tooltips for runes (provided by Blizzard) so there is not any reason to modify these. 

To keep it simple and user-friendly, I will add a checkbox to options to "Hide Undiscovered Runes".

Also, keep in mind this addon does *not* use data-mined data, nor is it utilizing anything from wowhead. It is simply using Blizzard's API which provides all the data in real-time

**Comment by mcd8604** [comment]
a2df001621210c018fd3fa17e11940301725e188
