### ISSUE TITLE
Hide head and wrists until phase 3

### ISSUE THREAD

**Issue by jhaubrich** [mcd8604/wowengraver#9]
We don't have runes for these slots yet.

https://www.wowhead.com/classic/news/confirmed-rune-slots-for-phase-2-head-and-wrist-slot-for-later-phases-season-of-337641

**Comment by mcd8604** [comment]
I'll look into this. For the time being, you can either check "Hide Undiscovered Runes" or use a filter that doesn't show the runes for these slots.
